# -*- coding: utf-8 -*-
"""Tufgas Akhir Judul 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BJpFW9GqtHqXHCwAf_U-lLbXYHFeoXAT
"""

def tukar(arr, i, j):
    temp = arr[i]
    arr[i] = arr[j]
    arr[j] = temp


def bubble_sort(arr, n):
    for i in range(n - 1):
        for j in range(n - i - 1):
            if arr[j] > arr[j + 1]:
                tukar(arr, j, j + 1)


def main():
    try:
        n = int(input("Masukkan jumlah mahasiswa: "))
    except ValueError:
        print("Input tidak valid!")
        return
    arr = []
    print("Masukkan jarak rumah mahasiswa (KM):")
    for i in range(n):
        while True:
            try:
                nilai = int(input())
                arr.append(nilai)
                break
            except ValueError:
                print("Input tidak valid, silakan masukkan angka!")
    print(f"Jarak rumah sebelum diurutkan (KM): {arr}")
    bubble_sort(arr, n)
    print("jarak rumah setelah diurutkan (KM):", end=" ")
    for i in range(n):
        print(arr[i], end=" ")
    print()


if __name__ == "__main__":
    main()